version: "3.9"
services:
    frontend:
        build:
            context: ./core/frontend/
            dockerfile: Dockerfile
        networks:
            - mynet
        ports:
            - "4200:4200"


volumes:
    data:

networks:
    mynet:
        driver: bridge
